### PR TITLE
UnknownRemoteApplicationEvent if deserialization fails

### LINKED ISSUE #48: Allow graceful handling of unknown subtypes of RemoteApplicationEvent in acceptRemote()
`BusAutoConfiguration.acceptRemote()` https://github.com/spring-cloud/spring-cloud-bus/blob/master/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/BusAutoConfiguration.java#L109 listens on `RemoteApplicationEvent`s from the Spring Cloud Stream side. When subclassing `RemoteApplicationEvent` for broadcasting own business events, every application needs to know all subclasses that can be received from Spring Cloud Stream, else deserialization of the concrete subclass of `RemoteApplicationEvent` will fail. In a microservice setting, this forces updates to ALL services that participate on the bus for every new event subtype introduced to avoid deserialization exceptions in non-upgraded services, even if these services are not interested in those new events.

I propose to gracefully handle the case of non-deserializable event subtypes of `RemoteApplicationEvent` by discarding those messages.

### PR DESCRIPTION
**Pull request by dl1ely**
Fixes #48.

If the Jackson deserializer cannot deserialize the event payload received,
it emits an UnknownRemoteApplicationEvent that wraps the type information
expected and the raw payload. Client applications can register on events
of type UnknownRemoteApplicationEvent and handle these cases
appropriately.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dl1ely Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-bus&pullRequestId=49)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-bus&pullRequestId=49) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dl1ely Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-bus&pullRequestId=49)!

File: spring-cloud-bus/src/main/java/org/springframework/cloud/bus/event/UnknownRemoteApplicationEvent.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+ * @author Stefan Pfeiffer
+ */
+public class UnknownRemoteApplicationEvent extends RemoteApplicationEvent {
+
+  protected String typeInfo;
+  protected byte[] payload;
+
+  @SuppressWarnings("unused")
+  private UnknownRemoteApplicationEvent() {
+    super();
```
Comment (spencergibb) [inline spring-cloud-bus/src/main/java/org/springframework/cloud/bus/event/UnknownRemoteApplicationEvent.java]: Formatting, we use tabs instead of spaces.

File: spring-cloud-bus/src/main/java/org/springframework/cloud/bus/jackson/BusJacksonAutoConfiguration.java [hunk 2]
```diff
@@ -105,10 +107,17 @@ public Object convertFromInternal(Message<?> message, Class<?> targetClass,
 			Object payload = message.getPayload();
 
 			if (payload instanceof byte[]) {
-				result = this.mapper.readValue((byte[]) payload, targetClass);
-			}
-			else if (payload instanceof String) {
-				result = this.mapper.readValue((String) payload, targetClass);
+			  try {
```
Comment (spencergibb) [inline spring-cloud-bus/src/main/java/org/springframework/cloud/bus/jackson/BusJacksonAutoConfiguration.java]: Again tabs.

**Comment by dl1ely** [comment]
Sorry, didn't notice. I was busy fighting Netbeans "auto-formatting on save" (and losing) before resorting to Atom editor ☺. Will fix it tomorrow.

**Comment by dl1ely** [comment]
@spencergibb Whats your policy on the @author javadoc field? Do i have to add myself in the files i changed, or is this supposed to be the initial author of the file?
